using System;

namespace VirtualPiano
{
    public class Arrays
    {
        static public string[] notes = {
            "C2",
            "C#2",
            "D2",
            "D#2",
            "E2",
            "F2",
            "F#2",
            "G2",
            "G#2",
            "A2",
            "A#2",
            "B2",
            "C3",
            "C#3",
            "D3",
            "D#3",
            "E3",
            "F3",
            "F#3",
            "G3",
            "G#3",
            "A3",
            "A#3",
            "B3",
            "C4",
            "C#4",
            "D4",
            "D#4",
            "E4",
            "F4",
            "F#4",
            "G4",
            "G#4",
            "A4",
            "A#4",
            "B4",
            "C5",
            "C#5",
            "D5",
            "D#5",
            "E5",
            "F5",
            "F#5",
            "G5",
            "G#5",
            "A5",
            "A#5",
            "B5",
            "C6",
            "C#6",
            "D6",
            "D#6",
            "E6",
            "F6",
            "F#6",
            "G6",
            "G#6",
            "A6",
            "A#6",
            "B6",
            "C7"
        };
        static public string[] keysString = {
            "1",
            "!",
            "2",
            "@",
            "3",
            "4",
            "$",
            "5",
            "%",
            "6",
            "^",
            "7",
            "8",
            "*",
            "9",
            "(",
            "0",
            "q",
            "Q",
            "w",
            "W",
            "e",
            "E",
            "r",
            "t",
            "T",
            "y",
            "Y",
            "u",
            "i",
            "I",
            "o",
            "O",
            "p",
            "P",
            "a",
            "s",
            "S",
            "d",
            "D",
            "f",
            "g",
            "G",
            "h",
            "H",
            "j",
            "J",
            "k",
            "l",
            "L",
            "z",
            "Z",
            "x",
            "c",
            "C",
            "v",
            "V",
            "b",
            "B",
            "n",
            "m",
            "|"
        };
        static public bool[] vpshift = {
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            false,
            true,
            false,
            true,
            false,
            true,
            false,
            false
    };
        static public ConsoleKey[] vp = {
            ConsoleKey.D1,
            ConsoleKey.D1, // !
            ConsoleKey.D2,
            ConsoleKey.D2, // @
            ConsoleKey.D3,
            ConsoleKey.D4,
            ConsoleKey.D4, // $
            ConsoleKey.D5,
            ConsoleKey.D5, // %
            ConsoleKey.D6,
            ConsoleKey.D6, // ^
            ConsoleKey.D7,
            ConsoleKey.D8,
            ConsoleKey.D8, //*
            ConsoleKey.D9,
            ConsoleKey.D9, // (
            ConsoleKey.D0,
            ConsoleKey.Q, // q
            ConsoleKey.Q,
            ConsoleKey.W, // w
            ConsoleKey.W,
            ConsoleKey.E, // e
            ConsoleKey.E,
            ConsoleKey.R, // r
            ConsoleKey.T, // t
            ConsoleKey.T,
            ConsoleKey.Y, // y 
            ConsoleKey.Y,
            ConsoleKey.U, // u
            ConsoleKey.I, // i
            ConsoleKey.I,
            ConsoleKey.O, // o
            ConsoleKey.O,
            ConsoleKey.P, // p
            ConsoleKey.P,
            ConsoleKey.A, // a
            ConsoleKey.S, // s
            ConsoleKey.S,
            ConsoleKey.D, // d
            ConsoleKey.D,
            ConsoleKey.F, // f
            ConsoleKey.G, // g
            ConsoleKey.G,
            ConsoleKey.H, // h
            ConsoleKey.H,
            ConsoleKey.J, // j
            ConsoleKey.J,
            ConsoleKey.K, // k
            ConsoleKey.L, // l
            ConsoleKey.L,
            ConsoleKey.Z, // z
            ConsoleKey.Z,
            ConsoleKey.X, // x
            ConsoleKey.C, // c
            ConsoleKey.C,
            ConsoleKey.V, // v
            ConsoleKey.V,
            ConsoleKey.B, // b
            ConsoleKey.B,
            ConsoleKey.N, // n
            ConsoleKey.M // m
        };
        static public int[] freq = {
            65,
            69,
            73,
            78,
            82,
            87,
            92,
            98,
            104,
            110,
            117,
            123,
            131,
            139,
            147,
            156,
            165,
            175,
            185,
            196,
            208,
            220,
            233,
            247,
            262,
            277,
            294,
            311,
            330,
            349,
            370,
            392,
            415,
            440,
            466,
            494,
            523,
            554,
            587,
            622,
            659,
            699,
            740,
            784,
            831,
            880,
            932,
            988,
            1046,
            1108,
            1174,
            1244,
            1318,
            1396,
            1480,
            1568,
            1661,
            1760,
            1864,
            1975,
            2093
        };
        
    }
}
